# ------------------------------------------------------------
# Chart configuration
# ------------------------------------------------------------
chart:
  title: ""
  t_min: 0
  t_max: 40
  y_min: 0.0
  y_max: 0.030
  pressure: 101325

# ------------------------------------------------------------
# Classical isolines
# ------------------------------------------------------------
isolines:
  relative_humidity:
    enabled: True
    color: "0.70"
    labels: True
    linewidth: 0.35
  enthalpy:
    enabled: True
    color: "0.75"
    labels: True
    linewidth: 0.25

indexes:
  - index: ITU
    label: ITU
    render:
      isolines:
        levels: [62, 68, 72, 78, 84, 90]
        color: "0.35"
        linewidth: 0.45
        style: ":"
        label: true

# ------------------------------------------------------------
# Domain index fields (theoretical)
# ------------------------------------------------------------
#index_fields:
#   - index: ITU
#     cmap: inferno
#     vmin: 60
#     vmax: 90
#     alpha: 0.5
#     parameters:
#        animal: dairy_cow

# ------------------------------------------------------------
# Observational datasets
# ------------------------------------------------------------
#observations:
#  - file: /media/extra/wrk/DADOS_CLEO/outros_dados/panting_zero.parquet
#    format: parquet
#
#    data_indexes:
#      - index: ICF
#        scatter: true
#        scalar_field: false
#        bins: [40, 40]
#        cmap: viridis
#        alpha: 0.6
#        colorbar: true
